// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Workout struct {
	ID          int32     `json:"id"`
	Exercise    string    `json:"exercise"`
	Sets        int32     `json:"sets"`
	Repetitions int32     `json:"repetitions"`
	Weight      string    `json:"weight"`
	WorkoutDate time.Time `json:"workout_date"`
}
