// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
    exercise,
    sets,
    repetitions,
    weight,
    workout_date
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, exercise, sets, repetitions, weight, workout_date
`

type CreateWorkoutParams struct {
	Exercise    string    `json:"exercise"`
	Sets        int32     `json:"sets"`
	Repetitions int32     `json:"repetitions"`
	Weight      string    `json:"weight"`
	WorkoutDate time.Time `json:"workout_date"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.Exercise,
		arg.Sets,
		arg.Repetitions,
		arg.Weight,
		arg.WorkoutDate,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Exercise,
		&i.Sets,
		&i.Repetitions,
		&i.Weight,
		&i.WorkoutDate,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE id = $1
`

func (q *Queries) DeleteWorkout(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteWorkout, id)
	return err
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, exercise, sets, repetitions, weight, workout_date
FROM workouts
WHERE id = $1
`

func (q *Queries) GetWorkout(ctx context.Context, id int32) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkout, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.Exercise,
		&i.Sets,
		&i.Repetitions,
		&i.Weight,
		&i.WorkoutDate,
	)
	return i, err
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, exercise, sets, repetitions, weight, workout_date
FROM workouts
ORDER BY workout_date DESC
`

func (q *Queries) ListWorkouts(ctx context.Context) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.Exercise,
			&i.Sets,
			&i.Repetitions,
			&i.Weight,
			&i.WorkoutDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkout = `-- name: UpdateWorkout :exec
UPDATE workouts
SET
    exercise = $2,
    sets = $3,
    repetitions = $4,
    weight = $5,
    workout_date = $6
WHERE id = $1
`

type UpdateWorkoutParams struct {
	ID          int32     `json:"id"`
	Exercise    string    `json:"exercise"`
	Sets        int32     `json:"sets"`
	Repetitions int32     `json:"repetitions"`
	Weight      string    `json:"weight"`
	WorkoutDate time.Time `json:"workout_date"`
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkout,
		arg.ID,
		arg.Exercise,
		arg.Sets,
		arg.Repetitions,
		arg.Weight,
		arg.WorkoutDate,
	)
	return err
}
